#!/bin/bash
# This Script for Updating you Kali Linux :)

if [[ $EUID -ne 0 ]]; then
clear
echo "

██╗░░░░░░░██╗██╗░█████╗░░█████╗░██████╗░██████╗░
██║░░░░░░██╔╝██║██╔═══╝░██╔═══╝░╚════██╗██╔══██╗
██║░░░░░██╔╝░██║██████╗░██████╗░░█████╔╝██████╔╝
██║░░░░░███████║██╔══██╗██╔══██╗░╚═══██╗██╔══██╗
███████╗╚════██║╚█████╔╝╚█████╔╝██████╔╝██║░░██║
╚══════╝░░░░░╚═╝░╚════╝░░╚════╝░╚═════╝░╚═╝░░╚═╝

" 
echo -e "   	\e[1;31m This Command must be Run as Root!\e[m"
exit 1
	fi
		clear
		figlet L4663R 
		apt-get update
		clear
		echo "Update Successfully! :D | Its Time to Upgrade your tools It take Long time so be Patients!"
		apt-get upgrade 
		clear
		echo "
██╗░░░░░░░██╗██╗░█████╗░░█████╗░██████╗░██████╗░
██║░░░░░░██╔╝██║██╔═══╝░██╔═══╝░╚════██╗██╔══██╗
██║░░░░░██╔╝░██║██████╗░██████╗░░█████╔╝██████╔╝
██║░░░░░███████║██╔══██╗██╔══██╗░╚═══██╗██╔══██╗
███████╗╚════██║╚█████╔╝╚█████╔╝██████╔╝██║░░██║
╚══════╝░░░░░╚═╝░╚════╝░░╚════╝░╚═════╝░╚═╝░░╚═╝"
		echo "ALL TOOLS ARE UPGRADE SUCCESSFULLY!"
		echo "Thanks for Using My script" 




